# Generated by Django 6.0.6 on 2026-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('profesion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('foto', models.ImageField(upload_to='testimonios/')),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
