# Generated by Django 5.2.6 on 2026-09-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonio',
        ),
    ]
