# Generated by Django 5.2.6 on 2026-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=200, verbose_name='Opinión')),
                ('tema', models.TextField(verbose_name='Tema')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('pdf', models.FileField(upload_to='documentos/opiniones/', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
                'ordering': ['-anio', '-fecha'],
            },
        ),
    ]
