# Generated by Django 5.2.6 on 2026-08-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='pdf',
            field=models.URLField(max_length=500, verbose_name='Enlace PDF'),
        ),
    ]
