# Generated by Django 6.0.6 on 2026-08-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('tipo', models.CharField(choices=[('vivo', 'Evento en Vivo'), ('virtual', 'Evento Virtual')], default='vivo', max_length=20)),
                ('horas', models.PositiveIntegerField(default=120)),
                ('semanas', models.PositiveIntegerField(default=7)),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
