# Generated by Django 5.2.6 on 2026-08-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('norma', 'Norma'), ('jurisprudencia', 'Jurisprudencia'), ('doctrina', 'Doctrina')], max_length=20, verbose_name='Categoría')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor / Institución')),
                ('año', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('pdf_url', models.URLField(verbose_name='URL del PDF')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
