# Generated by Django 5.2.6 on 2026-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tema', models.CharField(blank=True, max_length=255, verbose_name='Tema')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('pdf_url', models.URLField(verbose_name='URL del PDF')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('año', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jurisprudencia',
                'verbose_name_plural': 'Jurisprudencias',
                'ordering': ['-año', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
