# Generated by Django 5.2.6 on 2026-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_jurisprudencia_delete_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisprudencia',
            name='institucion',
            field=models.CharField(choices=[('oece', 'OECE'), ('contraloria', 'Contraloría'), ('tribunal_constitucional', 'Tribunal Constitucional')], default='oece', max_length=50, verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='jurisprudencia',
            name='tipo',
            field=models.CharField(choices=[('opinion', 'Opinión'), ('pronunciamiento', 'Pronunciamiento')], default='opinion', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='imagen_url',
            field=models.URLField(blank=True, verbose_name='URL de imagen Google Drive'),
        ),
    ]
