# Generated by Django 5.2.6 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


def convertir_instituciones(apps, schema_editor):
    Institucion = apps.get_model("biblioteca", "Institucion")
    Jurisprudencia = apps.get_model("biblioteca", "Jurisprudencia")

    oece = Institucion.objects.create(
        nombre="OECE",
        slug="oece",
        orden=1,
        activo=True,
    )

    contraloria = Institucion.objects.create(
        nombre="Contraloría",
        slug="contraloria",
        orden=2,
        activo=True,
    )

    tribunal = Institucion.objects.create(
        nombre="Tribunal Constitucional",
        slug="tribunal-constitucional",
        orden=3,
        activo=True,
    )

    for obj in Jurisprudencia.objects.all():

        if obj.institucion == "oece":
            obj.institucion_nueva_id = oece.id

        elif obj.institucion == "contraloria":
            obj.institucion_nueva_id = contraloria.id

        elif obj.institucion == "tribunal_constitucional":
            obj.institucion_nueva_id = tribunal.id

        else:
            obj.institucion_nueva_id = oece.id

        obj.save(update_fields=["institucion_nueva"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "biblioteca",
            "0003_jurisprudencia_institucion_jurisprudencia_tipo_and_more",
        ),
    ]

    operations = [

        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True,
                        verbose_name="URL de imagen Google Drive",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        verbose_name="Activo",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["orden", "nombre"],
            },
        ),

        migrations.AddField(
            model_name="jurisprudencia",
            name="institucion_nueva",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="biblioteca.institucion",
                verbose_name="Institución",
            ),
        ),

        migrations.RunPython(
            convertir_instituciones,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name="jurisprudencia",
            name="institucion",
        ),

        migrations.RemoveField(
            model_name="jurisprudencia",
            name="imagen_url",
        ),

        migrations.RenameField(
            model_name="jurisprudencia",
            old_name="institucion_nueva",
            new_name="institucion",
        ),

        migrations.AlterField(
            model_name="jurisprudencia",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jurisprudencias",
                to="biblioteca.institucion",
                verbose_name="Institución",
            ),
        ),
    ]