# Generated by Django 5.2.6 on 2026-08-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_institucion_remove_jurisprudencia_imagen_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='slug',
        ),
        migrations.AddField(
            model_name='institucion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='sigla',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='biblioteca.categoria')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('tema', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='biblioteca/documentos/')),
                ('pdf_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='biblioteca.categoria')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='biblioteca.institucion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='biblioteca.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-anio', '-fecha', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Jurisprudencia',
        ),
        migrations.AddConstraint(
            model_name='tipodocumento',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_tipo_documento_categoria'),
        ),
    ]
