# Generated by Django 5.2.6 on 2026-08-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_categoria_alter_institucion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='biblioteca/instituciones/'),
        ),
    ]
